"""Initial tables

Revision ID: 6a7714cc1580
Revises: 528dbc261b35
Create Date: 2026-02-10 10:13:28.527998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '6a7714cc1580'
down_revision: Union[str, Sequence[str], None] = '528dbc261b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('first_name', AutoString(), nullable=False),
    sa.Column('last_name', AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', AutoString(), nullable=False),
    sa.Column('phone_number', AutoString(length=15), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_first_name'), 'member', ['first_name'], unique=False)
    op.create_index(op.f('ix_member_last_name'), 'member', ['last_name'], unique=False)
    op.create_index(op.f('ix_member_phone_number'), 'member', ['phone_number'], unique=False)
    op.create_table('loan',
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payable_at', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('loan')
    op.drop_index(op.f('ix_member_phone_number'), table_name='member')
    op.drop_index(op.f('ix_member_last_name'), table_name='member')
    op.drop_index(op.f('ix_member_first_name'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
